# Generated by Django 5.0.3 on 2024-03-14 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cars', '0002_rename_brand_name_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_descr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='brand_rating',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
